cors:
  originPatterns:
    - http://localhost:3000
    - http://localhost:8080
    - http://localhost:8081
    - https://invictus.com.br

file:
  upload-dir: /home/ubuntu/portal-upload   # alterei para diretório da EC2

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portaldb?useTimezone=true&serverTimezone=UTC
    username: portaluser
    password: p3dr03th4n
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: erivelton.r.pinto@gmail.com
    password: p3dr03th4n
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

spring-doc:
  pathToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true